import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";
import { Layout } from "@/shared/ui/templates/layout";
import { HotelProvider } from "@/shared/context/hotel/hotel.context";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hotel Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <HotelProvider>
          <Layout>{children}</Layout>
        </HotelProvider>
      </body>
    </html>
  );
}
